"""Rasterise TTF fonts into anti-aliased VLW fonts embedded as a C header.

LovyanGFX's built-in fonts are 1-bit; VLW fonts carry an 8-bit alpha mask per
glyph, which is what makes the text on the display look smooth.

    python tools/make_fonts.py
"""
import struct
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

FONT_DIRS = [Path(r"C:\Windows\Fonts"), Path.home() / r"AppData\Local\Microsoft\Windows\Fonts"]

# name -> (file, pixel size)
FONTS = {
    "f_hero":  ("Roboto-Bold.ttf", 30),
    "f_title": ("Roboto-Bold.ttf", 16),
    "f_num":   ("Roboto-Bold.ttf", 19),
    "f_body":  ("Roboto-Regular.ttf", 14),
    "f_small": ("Roboto-Regular.ttf", 12),
    "f_mono":  ("JetBrainsMonoNerdFont-Medium.ttf", 12),
}

CHARS = [chr(c) for c in range(0x20, 0x7F)] + ["\u00b7", "\u2014", "\u2022", "\u2026"]

OUT = Path(__file__).resolve().parent.parent / "firmware" / "src" / "fonts.h"


def find(name: str) -> Path:
    for d in FONT_DIRS:
        p = d / name
        if p.exists():
            return p
    raise FileNotFoundError(name)


def vlw(path: Path, size: int) -> bytes:
    font = ImageFont.truetype(str(path), size)
    ascent, descent = font.getmetrics()
    glyphs, bitmaps = [], []
    for ch in sorted(CHARS, key=ord):
        adv = round(font.getlength(ch))
        x0, y0, x1, y1 = font.getbbox(ch, anchor="ls")
        w, h = max(0, x1 - x0), max(0, y1 - y0)
        if ch == " " or w == 0 or h == 0:
            glyphs.append((ord(ch), 0, 0, adv, 0, 0))
            continue
        img = Image.new("L", (w, h), 0)
        ImageDraw.Draw(img).text((-x0, -y0), ch, font=font, fill=255, anchor="ls")
        glyphs.append((ord(ch), h, w, adv, -y0, x0))
        bitmaps.append(img.tobytes())
    out = struct.pack(">6i", len(glyphs), 11, size, 0, ascent, descent)
    for g in glyphs:
        out += struct.pack(">7i", *g, 0)
    return out + b"".join(bitmaps)


def main() -> None:
    lines = ["// Generated by tools/make_fonts.py - do not edit.", "#pragma once", "#include <stdint.h>", ""]
    for name, (file, size) in FONTS.items():
        data = vlw(find(file), size)
        lines.append(f"// {file} @ {size}px, {len(data)} bytes")
        lines.append(f"static const uint8_t {name}_vlw[] = {{")
        for i in range(0, len(data), 24):
            lines.append("  " + ",".join(f"0x{b:02x}" for b in data[i:i + 24]) + ",")
        lines.append("};\n")
    OUT.write_text("\n".join(lines), encoding="ascii")
    print(f"wrote {OUT} ({OUT.stat().st_size // 1024} KB source)")


if __name__ == "__main__":
    main()
